In [19]:
import numpy as np
from numpy import array
from numpy.linalg import det

In [30]:
cov1 = array([1, 2, 3])
cov2 = array([6, 5, 6])
cov3 = array([7, 8, 9])

In [31]:
cov1

array([1, 2, 3])

In [35]:
cov = array([cov1, cov2, cov3])

In [45]:
covs = np.stack([cov, cov * 0.5, cov * 1.5])

In [46]:
covs

array([[[ 1. ,  2. ,  3. ],
        [ 6. ,  5. ,  6. ],
        [ 7. ,  8. ,  9. ]],

       [[ 0.5,  1. ,  1.5],
        [ 3. ,  2.5,  3. ],
        [ 3.5,  4. ,  4.5]],

       [[ 1.5,  3. ,  4.5],
        [ 9. ,  7.5,  9. ],
        [10.5, 12. , 13.5]]])

In [47]:
det(covs)

array([12. ,  1.5, 40.5])

In [29]:
# means
u1 = array([1, 1, 1])
u2 = array([4, 1, 7])
u3 = array([9, -1, 5])
means = np.stack([u1, u2, u3])

In [37]:
x  = array([1, 1, 1])

In [38]:
x - means

array([[ 0,  0,  0],
       [-3,  0, -6],
       [-8,  2, -4]])

In [48]:
print(covs[0] @ x)
print(covs[1] @ x)
print(covs[2] @ x)
print(covs @ x)

[ 6. 17. 24.]
[ 3.   8.5 12. ]
[ 9.  25.5 36. ]
[[ 6.  17.  24. ]
 [ 3.   8.5 12. ]
 [ 9.  25.5 36. ]]


In [51]:
print(covs)
print(covs.transpose())

[[[ 1.   2.   3. ]
  [ 6.   5.   6. ]
  [ 7.   8.   9. ]]

 [[ 0.5  1.   1.5]
  [ 3.   2.5  3. ]
  [ 3.5  4.   4.5]]

 [[ 1.5  3.   4.5]
  [ 9.   7.5  9. ]
  [10.5 12.  13.5]]]
[[[ 1.   0.5  1.5]
  [ 6.   3.   9. ]
  [ 7.   3.5 10.5]]

 [[ 2.   1.   3. ]
  [ 5.   2.5  7.5]
  [ 8.   4.  12. ]]

 [[ 3.   1.5  4.5]
  [ 6.   3.   9. ]
  [ 9.   4.5 13.5]]]


In [53]:
y = array([[[11,12], [21,22], [31,32]]])

In [54]:
y

array([[[11, 12],
        [21, 22],
        [31, 32]]])

In [55]:
y.shape

(1, 3, 2)

In [66]:
print(y.shape)
print(y.transpose((0, 1, 2)).shape)

print(y.transpose().shape)
print(y.transpose((2, 1, 0)).shape)

print(y.transpose(0, 2, 1).shape)




(1, 3, 2)
(1, 3, 2)
(2, 3, 1)
(2, 3, 1)
(1, 2, 3)


In [68]:
print(y.transpose(0, 2, 1))

[[[11 21 31]
  [12 22 32]]]
